name: multirl
channels:
  - defaults
  - conda-forge
dependencies:
  # Core dependencies
  - python==3.10.*
  - redis==5.0.3
  - redis-py==3.4.1

  # Data analysis and viz
  - matplotlib==3.5.*
  - pandas==1.*

  # Dev
  - jupyterlab
  - pytest
  - flake8
  - psutil
  - tqdm

  # Pip packages for all of them
  - pip
  - pip:
      # Workflow tools
      - funcx_endpoint
      - colmena==0.4.*
      - parsl==2023.2.20
